[Feature/step7] Webのフロントエンドを実装する
kotapiku/mercari-build-training-2023 pull request #6
Opened 2023-05-16 17:21 UTC by kotapiku

## What
- 新しい商品を登録できるようにした
- 各アイテムの画像を表示するようにした
- アイテム一覧とフォームのUIをmaterial UIを使って以下の画像のように変更した
<img width="713" alt="image" src="https://github.com/mercari-build/mercari-build-training-2023/assets/25437132/b3832bb8-1cf4-4222-a4ba-24bf9aff20c5">

## CHECKS :warning:

Please make sure you are aware of the following.

- [x] **The changes in this PR doesn't have private information

2023-05-17 06:21 UTC, NamikoToriyama commented on typescript/simple-mercari-web/src/App.tsx
> +            {/* </header> */}
[nits] TSのコメントはBuildで失敗する原因になることもあるので、コメント消しましょう。

2023-05-17 06:21 UTC, NamikoToriyama commented on typescript/simple-mercari-web/src/App.tsx
> +                    >Simple Mercari</Typography>
[nits]この部分少し気になりますね。formatterとかかけるといいかもしれません。Prettierとかおすすめです。

ref:
https://prettier.io/docs/en/install.html

2023-05-17 15:31 UTC, kotapiku commented on typescript/simple-mercari-web/src/App.tsx
> +                    >Simple Mercari</Typography>
ありがとうございます、prettier使ってみました。

2023-05-17 16:25 UTC, kotapiku commented
I updated UI:
<img width="909" alt="image" src="https://github.com/kotapiku/mercari-build-training-2023/assets/25437132/21f6122b-177c-410c-9ebd-748c96aed32d">

2023-05-18 01:08 UTC, ken-kentan approved these changes
LGTM!

無関係のフォーマット変更（例えば `'` -> `"`など）がPRに含まれるとどの部分が意図して変えたのか分からなくなってしまうので現状のフォーマットを保つか別にPRを出してもらえると助かります。

2023-05-18 01:08 UTC, ken-kentan commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
> +        Accept: "application/json",
Acceptも `""`で宣言した方が良いと思います

2023-05-18 04:02 UTC, NamikoToriyama approved these changes

2023-05-18 14:14 UTC, togami2864 requested changes
@NamikoToriyama に斡旋されてきた??フロントエンドエンジニアのものです。
いくつか気になる点があったのでコメントしておきました！！概ねReactのつまづきやすい部分はバッチリでした👍

2023-05-18 14:14 UTC, togami2864 commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
>    const fetchItems = () => {
関数内で`await`を使うために`async`をつけておく必要があります！(async, awaitについては後述)
```suggestion
  const fetchItems = async() => {
```

2023-05-18 14:14 UTC, togami2864 commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
> +    fetch(server.concat("/items"), {
`fetch`は`Promise`を返す非同期関数なので、呼び出す時に`await`をつける必要があります。なお、`await`は基本的に`async`がついた関数の中でしか呼び出せません。
```suggestion
    await fetch(server.concat("/items"), {
```
非同期関数(今回はfetch)に対して`await`を使わないと**その関数の処理が終わる前に次の処理が始まってしまいます**

今回のケースではあまり問題になっていませんが、より複雑なエラー処理をするときや、`fetch`の結果をもとに処理を行いたいときに不具合の原因になります。

2023-05-18 14:14 UTC, togami2864 commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
> +        console.log("GET success:", data);
極力いらない`console.log`は消しておきましょう(もちろん開発中はガンガン使ってOKです！)

2023-05-18 14:14 UTC, togami2864 commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
> +        console.log(item.image_filename);
ditto

2023-05-18 14:14 UTC, togami2864 commented on typescript/simple-mercari-web/src/components/Listing/Listing.tsx
>    const onSubmit = (event: React.FormEvent<HTMLFormElement>) => {
同じく`async`関数にしてあげましょう
```suggestion
  const onSubmit = async(event: React.FormEvent<HTMLFormElement>) => {
```

2023-05-18 14:14 UTC, togami2864 commented on typescript/simple-mercari-web/src/components/Listing/Listing.tsx
> +    fetch(server.concat("/items"), {
同じく`await`をつけてあげましょう
```suggestion
    await fetch(server.concat("/items"), {
```

2023-05-18 14:16 UTC, kotapiku commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
> +        Accept: "application/json",
prettierがダブルクオートを消せる場合は消す仕様になっていて、Content-Typeのほうはハイフンがあるせいで消さないために起こっているみたいです。(参考：https://github.com/prettier/prettier-atom/issues/292 )

2023-05-18 14:21 UTC, kotapiku commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
> +        Accept: "application/json",
なおしました！

2023-05-18 14:25 UTC, kotapiku commented on typescript/simple-mercari-web/src/components/Listing/Listing.tsx
> +    fetch(server.concat("/items"), {
丁寧なレビューありがとうございます！反映しました

2023-05-18 14:30 UTC, kotapiku commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
> +    fetch(server.concat("/items"), {
`then`と`catch`を使っているから処理してから次にいくと思ったのですが`await`を使わないと困ることがあるのでしょうか？
そもそも`then`, `catch`を使わず`await`を使ったほうがいいですか？

2023-05-18 16:31 UTC, merged

2023-05-18 16:57 UTC, togami2864 commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
> +    fetch(server.concat("/items"), {
あーーごめんなさい😭
ちゃんと後続処理もちゃんとチェーンで描いてるのでこのパターンでは不要でしたね。大変失礼しました🙇
また、今回のようにシンプルなパターンではthen/catchで全く問題ありません。(Listing.tsxの方も同様です🙇)

じゃあ同じことが出来るのになぜasync/awaitがあるかというと主に可読性や保守性の観点から選択することが多いです。
現実的なユースケースとして、通信後に
- snaqbarやloading barなどのUIのためのstateやglobalなstateを複数更新したい
- 受け取ったレスポンスからさらに細かく分岐して画面を遷移させたい
- エラーのstatusから文言を決定したい
- さらに別の非同期処理を呼び出したい

といった動作が増えた時、then/catchの中のネストがどんどん深くなっていく場合があります。
そういう時にasync/awaitを使ってかくと読みやすいコードになるため、コードが複雑になりやすい大きい開発だと好まれます。(特に非同期からさらに別の非同期は開発中頻繁にでくわします。)

2023-05-19 02:07 UTC, kotapiku commented on typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
> +    fetch(server.concat("/items"), {
なるほどです！ありがとうございます:bow: